# Generated by Django 2.2.13 on 2020-08-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('objective', models.TextField()),
                ('skills', models.TextField()),
                ('workexperience', models.TextField()),
                ('education', models.TextField()),
                ('landuages', models.TextField()),
            ],
        ),
    ]
