# Generated by Django 2.2.13 on 2020-08-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='landuages',
            new_name='languages',
        ),
    ]
